name: Check Passed Tests

on:
  pull_request:
    #    branches:
    #      - main
    types:
      - opened
      - labeled
      - unlabeled

jobs:
  fail-for-draft:
    if: !contains(github.event.pull_request.labels.*.name, 'passed-all-tests')
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR is a draft
        run: |
          echo "This PR is currently a draft."
          exit 1